### ISSUE TITLE
datasets from the KDD'16 paper

### ISSUE THREAD

**Issue by kliegr** [lvhimabindu/interpretable_decision_sets#2]
The KDD'16 paper provides evaluation on three datasets: bail outcomes, medical diagnosis and student performance. While references are provided in the paper, I was not able to get access to them. Would it be possible to provide these datasets? Thanks

**Comment by lvhimabindu** [comment]
Unfortunately, these datasets are under NDAs. We tried to get permissions to make them public but we have not been successful.
